f123();
console.log(1);
console.log(2);
console.log(3);
console.log('A');
console.log('Z');
console.log('B');
f123();
console.log(1);
console.log(2);
console.log(3);
console.log('f');
console.log('C');
console.log('P');
console.log('J');
f123();
console.log(1);
console.log(2);
console.log(3);
console.log('U');
console.log('Z');
console.log('I');
console.log('R');
f123();
console.log(1);
console.log(2);
console.log(3);

function f123(){
    console.log(1);
    console.log(2);
    console.log(3);
    console.log(4);
}